"$schema" = "https://starship.rs/config-schema.json"

scan_timeout = 200

[battery]
full_symbol = "‚Ä¢ "
charging_symbol = "‚á° "
discharging_symbol = "‚á£ "
unknown_symbol = "‚ùì "
empty_symbol = "‚ùó "

[erlang]
symbol = "‚ìî "

[fortran]
symbol = "F "

[nodejs]
symbol = "[‚¨¢](bold green) "

[pulumi]
symbol = "üßä "

[typst]
symbol = "t "

[custom.screen]
description = "Displays whether we are in a screen session"
command = "echo screen"
when = """test -n "$STY" """
format = "in [$symbol($output )]($style)"
style = "bold yellow"

[custom.tmux]
description = "Displays whether we are in a tmux session"
command = 'tmux display-message -p "#S"'
when = 'test -n "$TMUX"'
#format = "in [$symbol($output )]($style)"
style = "bold yellow"
symbol = "‚ñ£ "
